version: '3.8'
services:
  app:
    build: 
      context: .
      args:
        - CONTAINER_INTERNAL_PORT=${CONTAINER_INTERNAL_PORT:-8080}
    ports:
      - "${DOCKER_HOST_PORT:-3001}:${CONTAINER_INTERNAL_PORT:-8080}"
    env_file:
      - .env
    environment:
      - STREAMLIT_SERVER_PORT=${STREAMLIT_SERVER_PORT:-8080}
      - STREAMLIT_SERVER_ADDRESS=${STREAMLIT_SERVER_ADDRESS:-0.0.0.0}
      - STREAMLIT_SERVER_ENABLE_CORS=${STREAMLIT_SERVER_ENABLE_CORS:-false}
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=${STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION:-true}
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=${STREAMLIT_BROWSER_GATHER_USAGE_STATS:-false}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${STREAMLIT_SERVER_PORT}/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
