name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr libgl1-mesa-glx

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 
    
    - name: Create .env file
      run: |
        echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
        echo "RAPIDAPI_KEY=${{ secrets.RAPIDAPI_KEY }}" >> .env
    
    - name: Run tests
      run: |
        pytest test_basketball_analyst.py
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
    
    - name: Build Streamlit app
      run: |
        # Placeholder for any build steps if needed
        streamlit hello  # Verify Streamlit installation
